version: "0.5"

processes:
  tailwind:
    command: tailwindcss -i src/frontend/styles/booking.css -o src/backend/wwwroot/styles.css --watch=always

  elm:
    command: |
      cd src/frontend/booking
      elm make src/Main.elm --output=../../backend/wwwroot/booking.js
      inotifywait -m -r -e modify,create,delete src/ |
        while read -r; do
          sleep 0.3
          elm make src/Main.elm --output=../../backend/wwwroot/booking.js
        done

  backend:
    command: dotnet watch --no-hot-reload run --project src/backend/Michael.fsproj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://localhost:8000
    shutdown:
      signal: 15
      timeout_seconds: 5
